backend:
    name: github
    repo: akingdebased/fls-international
    branch: master # Branch to update (optional; defaults to master)

local_backend: true # TODO: Check if this prohibits the CMS from running on Netlify (production)

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: /assets
collections:
    - name: pages
      label: Pages
      create: true # TODO: Should probably be false, but need to figure out how this works
      files:
          - file: 'src/pages/home/home.md'
            label: 'Home Page'
            name: 'home'
            fields:
                - widget: 'object' # TODO: This widget needs to be expanded to allow custom carousel items
                  label: 'Hero Banner Settings'
                  name: 'carousel_settings'
                  fields:
                      - { label: 'Title', name: 'title', widget: 'text' }
                      - { label: 'Copy', name: 'copy', widget: 'text' }
                - widget: 'object'
                  label: 'Explore Your World'
                  name: 'explore_your_world'
                  fields:
                      - { label: 'Title', name: 'title', widget: 'text' }
                      - { label: 'Subtitle', name: 'subtitle', widget: 'text' }
                      - { label: 'Copy', name: 'copy', widget: 'text' }
                - widget: 'object'
                  label: 'Start Your Journey'
                  name: 'start_your_journey'
                  fields:
                      - { label: 'Title', name: 'title', widget: 'text' }
                      - { label: 'Subtitle', name: 'subtitle', widget: 'text' }
                      - { label: 'Copy', name: 'copy', widget: 'text' }
                - widget: 'object'
                  label: 'Our Popular Programs'
                  name: 'our_popular_programs'
                  fields:
                      - { label: 'Title', name: 'title', widget: 'text' }
                      - { label: 'Subtitle', name: 'subtitle', widget: 'text' }
                      - { label: 'Copy', name: 'copy', widget: 'text' }
                - widget: 'object'
                  label: 'How Is Your English?'
                  name: 'how_is_your_english'
                  fields:
                      - { label: 'Title', name: 'title', widget: 'text' }
                      - { label: 'Subtitle', name: 'subtitle', widget: 'text' }
                      - { label: 'Copy', name: 'copy', widget: 'text' }
          - file: 'src/pages/programs/programs.md'
            label: 'Programs Page'
            name: 'programs'
            fields:
                - widget: 'list'
                  name: 'program_cards'
                  label: 'Program Cards'
                  allow_add: true
                  fields:
                      - {
                            label: 'Card Title',
                            name: 'card_title',
                            widget: string,
                            default: 'English Language Programs',
                        }
                      - {
                            label: 'Card Description',
                            name: 'card_description',
                            widget: text,
                            default: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae tincidunt massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada finibus tincidunt. Ut maximus ipsum non ultrices mattis. Interdum et malesuada fames ac ante ipsum primis in faucibus.',
                        }
                      - { label: Card Image, name: card_image, widget: image }
    - name: application
      label: Application
      create: false # TODO: Should probably be false, but need to figure out how this works
      files:
          # TODO: Figure out where this file's true home is
          - file: 'src/pages/application-landing.md'
            label: 'Application Landing'
            name: 'application-landing'
            fields:
                - widget: 'object'
                  label: 'On Location Program Information'
                  name: 'on-location-program-information'
                  fields:
                      - {
                            label: 'General Fees',
                            name: 'general-fees',
                            widget: 'object',
                            fields:
                                [
                                    {
                                        name: 'application_fee',
                                        label: 'Application Fee',
                                        widget: 'number',
                                    },
                                    {
                                        name: 'housing_placement_fee',
                                        label: 'Housing Placement Fee',
                                        widget: 'number',
                                    },
                                    {
                                        name: 'health_insurance_fee',
                                        label: 'Health Insurance Fee (Weekly)',
                                        widget: 'number',
                                    },
                                    {
                                        label: 'One-on-One Tutoring (per lesson)',
                                        name: 'tutoring',
                                        widget: 'number',
                                    },
                                    {
                                        label: 'Express Mail Fee (I-20 Applicants)',
                                        name: 'express_mail_fee',
                                        widget: 'number',
                                    },
                                    {
                                        label: 'Extra Night: Homestay (per night)',
                                        name: 'extra_night_homestay',
                                        widget: 'number',
                                    },
                                    {
                                        label: 'Extra Night: Student Resources (per night)',
                                        name: 'extra_night_resources',
                                        widget: 'number',
                                    },
                                    {
                                        label: 'Books and Materials',
                                        name: 'books_and_materials',
                                        widget: 'number',
                                    },
                                ],
                        }
                      - {
                            label: 'Locations',
                            name: 'locations',
                            allow_add: true,
                            widget: 'list',
                            fields:
                                [
                                    {
                                        label: 'Location Name',
                                        name: 'location_name',
                                        widget: 'string',
                                    },
                                    {
                                        label: 'Programs',
                                        name: 'programs',
                                        widget: 'list',
                                        fields:
                                            [
                                                {
                                                    label: 'Program Name',
                                                    name: 'program_name',
                                                    widget: 'string',
                                                },
                                                {
                                                    label: 'Program Details',
                                                    name: 'program-details',
                                                    widget: 'object',
                                                    fields:
                                                        [
                                                            {
                                                                name: 'duration',
                                                                label: 'Duration (Weeks)',
                                                                widget: 'string',
                                                            },
                                                            {
                                                                name: 'price',
                                                                label: 'Price (USD)',
                                                                widget: 'number',
                                                            },
                                                            {
                                                                name: 'hours',
                                                                label: 'Hours (Per Week)',
                                                                widget: 'number',
                                                            },
                                                            {
                                                                name: 'lessons',
                                                                label: 'Lessons (Per Week)',
                                                                widget: 'number',
                                                            },
                                                        ],
                                                },
                                            ],
                                    },
                                ],
                        }
