backend:
    name: github
    repo: akingdebased/fls-international
    branch: master # Branch to update (optional; defaults to master)

local_backend: true # TODO: Check if this prohibits the CMS from running on Netlify (production)

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: /assets
collections:
    - name: pages
      label: Pages
      create: true # TODO: Should probably be false, but need to figure out how this works
      files:
          - file: 'src/netlify-content/pages/home/home.md'
            label: 'Home Page'
            name: 'home'
            fields:
                - widget: 'object' # TODO: This widget needs to be expanded to allow custom carousel items
                  label: 'Hero Banner Settings'
                  name: 'carousel_settings'
                  fields:
                      - { label: 'Title', name: 'title', widget: 'text' }
                      - { label: 'Copy', name: 'copy', widget: 'text' }
                - widget: 'object'
                  label: 'Explore Your World'
                  name: 'explore_your_world'
                  fields:
                      - { label: 'Title', name: 'title', widget: 'text' }
                      - { label: 'Subtitle', name: 'subtitle', widget: 'text' }
                      - { label: 'Copy', name: 'copy', widget: 'text' }
                - widget: 'object'
                  label: 'Start Your Journey'
                  name: 'start_your_journey'
                  fields:
                      - { label: 'Title', name: 'title', widget: 'text' }
                      - { label: 'Subtitle', name: 'subtitle', widget: 'text' }
                      - { label: 'Copy', name: 'copy', widget: 'text' }
                - widget: 'object'
                  label: 'Our Popular Programs'
                  name: 'our_popular_programs'
                  fields:
                      - { label: 'Title', name: 'title', widget: 'text' }
                      - { label: 'Subtitle', name: 'subtitle', widget: 'text' }
                      - { label: 'Copy', name: 'copy', widget: 'text' }
                - widget: 'object'
                  label: 'How Is Your English?'
                  name: 'how_is_your_english'
                  fields:
                      - { label: 'Title', name: 'title', widget: 'text' }
                      - { label: 'Subtitle', name: 'subtitle', widget: 'text' }
                      - { label: 'Copy', name: 'copy', widget: 'text' }
          - file: 'src/netlify-content/pages/programs.md'
            label: 'Programs Page'
            name: 'programs'
            fields:
                - widget: 'list'
                  name: 'program_cards'
                  label: 'Program Cards'
                  allow_add: true
                  fields:
                      - {
                            label: 'Card Title',
                            name: 'card_title',
                            widget: string,
                            default: 'English Language Programs',
                        }
                      - {
                            label: 'Card Description',
                            name: 'card_description',
                            widget: text,
                            default: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae tincidunt massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada finibus tincidunt. Ut maximus ipsum non ultrices mattis. Interdum et malesuada fames ac ante ipsum primis in faucibus.',
                        }
                      - { label: Card Image, name: card_image, widget: image }
    - name: 'location'
      label: 'Location'
      create: true
      folder: 'src/netlify-content/location'
      identifier_field: slug
      fields:
          # See if there's a way to add descriptive text to these fields
          - { label: 'Slug', name: 'slug', widget: 'string' }
          - { label: 'Name', name: 'name', widget: 'string' }
          - {
                label: 'General Fees',
                name: 'general-fees ',
                widget: 'list',
                fields:
                    # TODO: Something is weird about the nesting here, it's adding an extra layer in the parsed object
                    [
                        { label: 'Name', name: 'Name', widget: 'string' },
                        { label: 'Cost', name: 'cost', widget: 'number' },
                    ],
            }
          - {
                label: 'Programs',
                name: 'programs',
                widget: 'list',
                fields:
                    [
                        { label: 'Name', name: 'name', widget: 'string' },
                        {
                            label: 'Max Weeks',
                            name: 'max-weeks',
                            widget: 'string',
                        },
                        {
                            label: 'Exceed max weeks?',
                            name: 'exceed-max-weeks',
                            required: false,
                            widget: 'boolean',
                        },
                        {
                            label: 'Week Thresholds',
                            name: 'week-thresholds',
                            widget: 'list',
                            fields:
                                [
                                    {
                                        label: 'Threshold Max',
                                        name: 'threshold-max',
                                        widget: 'number',
                                    },
                                    {
                                        label: 'Price Per Week',
                                        name: 'price-per-week',
                                        widget: 'number',
                                    },
                                    {
                                        label: 'Hours Per Week',
                                        name: 'hours-per-week',
                                        widget: 'number',
                                    },
                                    {
                                        label: 'Lessons Per Week',
                                        name: 'lessons-per-week',
                                        widget: 'number',
                                    },
                                ],
                        },
                    ],
            }
          - {
                label: 'Supplements',
                name: 'supplements',
                widget: 'object',
                fields: [
                        {
                            label: 'Airport Transfers',
                            name: 'airport-transfers',
                            widget: 'list',
                            allow_add: true,
                            fields:
                                [
                                    {
                                        label: 'Airport Name',
                                        name: 'airport-name',
                                        widget: 'string',
                                    },
                                    {
                                        label: 'Cost',
                                        name: 'cost',
                                        widget: 'number',
                                    },
                                ],
                        },
                        {
                            # TODO: Do we need to capture "per x unit class"?
                            # TODO: Also note, how do we capture the 'sublocations' that Boston Commons has?
                            label: 'Concurrent Enrollment',
                            name: 'concurrent-enrollment',
                            widget: 'object',
                            fields:
                                [
                                    {
                                        label: 'Per 3 unit class',
                                        name: 'per-3-unit-class',
                                        widget: 'number',
                                    },
                                ],
                        },
                        {
                            # TODO: How do we capture the amount for 4 weeks, and the amount each additional week?
                            label: 'Auditing',
                            name: 'auditing',
                            widget: 'object',
                            fields:
                                [
                                    {
                                        label: '4 Week Cost',
                                        name: '4-week-cost',
                                        widget: 'number',
                                    },
                                    {
                                        label: 'Additional week cost',
                                        name: 'additional-week-cost',
                                        widget: 'number',
                                    },
                                ],
                        },
                        {
                            # TODO: Do we need to capture "per x unit class"?
                            label: 'High School Completion Course',
                            name: 'hs-completion-course',
                            widget: 'object',
                            fields:
                                [
                                    {
                                        label: '4 Week Cost',
                                        name: '4-week-cost',
                                        widget: 'number',
                                    },
                                    {
                                        label: 'Additional week cost',
                                        name: 'additional-week-cost',
                                        widget: 'number',
                                    },
                                ],
                        },
                        {
                            # TODO: Do we need to capture "per x unit class"?
                            label: 'High School Immersion',
                            name: 'hs-immersion',
                            widget: 'object',
                            fields:
                                [
                                    {
                                        label: 'Per week cost',
                                        name: 'per-week-cost',
                                        widget: 'number',
                                    },
                                ],
                        },
                    ],
            }
          - {
                label: 'Housing Fees',
                name: 'housing-fees',
                widget: 'list',
                fields: [
                        {
                            label: 'Housing Name',
                            name: 'housing-name',
                            widget: 'string',
                        },
                        {
                            label: 'Meals per week',
                            name: 'meals-per-week',
                            widget: 'number',
                        },
                        {
                            label: 'Cost Per Week',
                            name: 'cost-per-week',
                            widget: 'number',
                        },
                        {
                            label: 'Non-refundable Deposit',
                            name: 'non-refundable-deposit',
                            widget: 'number',
                        },
                        {
                            label: 'Additional Notes',
                            name: 'additional-notes',
                            widget: 'list',
                            # TODO: When creating new notes, they come wrapped in another object. I don't think this is intended behavior
                            field:
                                {
                                    label: 'Note',
                                    name: 'note',
                                    widget: 'string',
                                },
                        },
                    ],
            }
